// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yazilim_mimari.Data.Context;

#nullable disable

namespace yazilim_mimari.Migrations
{
    [DbContext(typeof(AracSatisContext))]
    [Migration("20240522155253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("yazilim_mimari.Data.Models.Arac", b =>
                {
                    b.Property<int>("AracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CamTavan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KatlanabilirAyna")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int");

                    b.Property<bool>("MerkeziKilit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<bool>("ParkSensoru")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sanziman")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SisFari")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UretimYili")
                        .HasColumnType("int");

                    b.Property<string>("YakitTuru")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AracId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("ModelId");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.AracModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int");

                    b.Property<string>("ModelAdi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ModelId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("ModelAdi")
                        .IsUnique();

                    b.ToTable("Modeller");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Ilan", b =>
                {
                    b.Property<int>("IlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AdminOnayladiMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Fiyat")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Resimler")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("YayindaMi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IlanId");

                    b.HasIndex("AracId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Ilanlar");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Istek", b =>
                {
                    b.Property<int>("IstekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.HasKey("IstekId");

                    b.HasIndex("IlanId");

                    b.ToTable("Istekler");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Kullanici", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Ad = "Alperen",
                            Eposta = "alperendilaver.0@gmail.com",
                            Password = "Alperen.67",
                            Role = "Admin",
                            Soyad = "Dilaver"
                        },
                        new
                        {
                            UserId = 2,
                            Ad = "Alperen",
                            Eposta = "alperendilaver@gmail.com",
                            Password = "Alperen.67",
                            Role = "Uye",
                            Soyad = "Dilaver"
                        });
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Marka", b =>
                {
                    b.Property<int>("MarkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MakeName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("MarkaId");

                    b.HasIndex("MakeName")
                        .IsUnique();

                    b.ToTable("Markalar");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Yorum", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YorumIcerik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("YorumId");

                    b.HasIndex("IlanId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Arac", b =>
                {
                    b.HasOne("yazilim_mimari.Data.Models.Marka", "Marka")
                        .WithMany()
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yazilim_mimari.Data.Models.AracModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marka");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.AracModel", b =>
                {
                    b.HasOne("yazilim_mimari.Data.Models.Marka", "Marka")
                        .WithMany()
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Ilan", b =>
                {
                    b.HasOne("yazilim_mimari.Data.Models.Arac", "arac")
                        .WithMany()
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yazilim_mimari.Data.Models.Kullanici", "kullanici")
                        .WithMany("KullaniciIlanlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("arac");

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Istek", b =>
                {
                    b.HasOne("yazilim_mimari.Data.Models.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Yorum", b =>
                {
                    b.HasOne("yazilim_mimari.Data.Models.Ilan", "Ilan")
                        .WithMany("Yorumlar")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("yazilim_mimari.Data.Models.Kullanici", "kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Ilan", b =>
                {
                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("yazilim_mimari.Data.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciIlanlari");
                });
#pragma warning restore 612, 618
        }
    }
}
